source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HFTAGManager_Example', :exclusive => true do
  pod "HFTAGManager", :path => "../"
end

target 'HFTAGManager_Tests', :exclusive => true do
  pod "HFTAGManager", :path => "../"

  pod 'Kiwi'
end
