source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'10.0'
use_frameworks!

target 'HFTAGManager_Example' do
  pod "HFTAGManager", :path => "../"
end

target 'HFTAGManager_Tests' do
  pod "HFTAGManager", :path => "../"

  pod 'Kiwi'
  pod 'LeakCanaryiOS'
end
